export const VietNamProvince = [
  {
    name: "Hanoi City",
    code: 1,
    division_type: "central city",
    codename: "hanoi_city",
    phone_code: 24,
    districts: [],
  },
  {
    name: "Ha Giang Province",
    code: 2,
    division_type: "province",
    codename: "ha_giang_province",
    phone_code: 219,
    districts: [],
  },
  {
    name: "Cao Bang Province",
    code: 4,
    division_type: "province",
    codename: "cao_bang_province",
    phone_code: 206,
    districts: [],
  },
  {
    name: "Bac Kan Province",
    code: 6,
    division_type: "province",
    codename: "bac_kan_province",
    phone_code: 209,
    districts: [],
  },
  {
    name: "Tuyen Quang Province",
    code: 8,
    division_type: "province",
    codename: "tuyen_quang_province",
    phone_code: 207,
    districts: [],
  },
  {
    name: "Lao Cai Province",
    code: 10,
    division_type: "province",
    codename: "lao_cai_province",
    phone_code: 214,
    districts: [],
  },
  {
    name: "Dien Bien Province",
    code: 11,
    division_type: "province",
    codename: "dien_bien_province",
    phone_code: 215,
    districts: [],
  },
  {
    name: "Lai Chau Province",
    code: 12,
    division_type: "province",
    codename: "lai_chau_province",
    phone_code: 213,
    districts: [],
  },
  {
    name: "Son La Province",
    code: 14,
    division_type: "province",
    codename: "son_la_province",
    phone_code: 212,
    districts: [],
  },
  {
    name: "Yen Bai Province",
    code: 15,
    division_type: "province",
    codename: "yen_bai_province",
    phone_code: 216,
    districts: [],
  },
  {
    name: "Hoa Binh Province",
    code: 17,
    division_type: "province",
    codename: "hoa_binh_province",
    phone_code: 218,
    districts: [],
  },
  {
    name: "Thai Nguyen Province",
    code: 19,
    division_type: "province",
    codename: "thai_nguyen_province",
    phone_code: 208,
    districts: [],
  },
  {
    name: "Lang Son Province",
    code: 20,
    division_type: "province",
    codename: "lang_son_province",
    phone_code: 205,
    districts: [],
  },
  {
    name: "Quang Ninh Province",
    code: 22,
    division_type: "province",
    codename: "quang_ninh_province",
    phone_code: 203,
    districts: [],
  },
  {
    name: "Bac Giang Province",
    code: 24,
    division_type: "province",
    codename: "bac_giang_province",
    phone_code: 204,
    districts: [],
  },
  {
    name: "Phu Tho Province",
    code: 25,
    division_type: "province",
    codename: "phu_tho_province",
    phone_code: 210,
    districts: [],
  },
  {
    name: "Vinh Phuc Province",
    code: 26,
    division_type: "province",
    codename: "vinh_phuc_province",
    phone_code: 211,
    districts: [],
  },
  {
    name: "Bac Ninh Province",
    code: 27,
    division_type: "province",
    codename: "bac_ninh_province",
    phone_code: 222,
    districts: [],
  },
  {
    name: "Hai Duong Province",
    code: 30,
    division_type: "province",
    codename: "hai_duong_province",
    phone_code: 220,
    districts: [],
  },
  {
    name: "Hai Phong City",
    code: 31,
    division_type: "central city",
    codename: "hai_phong_city",
    phone_code: 225,
    districts: [],
  },
  {
    name: "Hung Yen Province",
    code: 33,
    division_type: "province",
    codename: "hung_yen_province",
    phone_code: 221,
    districts: [],
  },
  {
    name: "Thai Binh Province",
    code: 34,
    division_type: "province",
    codename: "thai_binh_province",
    phone_code: 227,
    districts: [],
  },
  {
    name: "Ha Nam Province",
    code: 35,
    division_type: "province",
    codename: "ha_nam_province",
    phone_code: 226,
    districts: [],
  },
  {
    name: "Nam Dinh Province",
    code: 36,
    division_type: "province",
    codename: "nam_dinh_province",
    phone_code: 228,
    districts: [],
  },
  {
    name: "Ninh Binh Province",
    code: 37,
    division_type: "province",
    codename: "ninh_binh_province",
    phone_code: 229,
    districts: [],
  },
  {
    name: "Thanh Hoa Province",
    code: 38,
    division_type: "province",
    codename: "thanh_hoa_province",
    phone_code: 237,
    districts: [],
  },
  {
    name: "Nghe An Province",
    code: 40,
    division_type: "province",
    codename: "nghe_an_province",
    phone_code: 238,
    districts: [],
  },
  {
    name: "Ha Tinh Province",
    code: 42,
    division_type: "province",
    codename: "ha_tinh_province",
    phone_code: 239,
    districts: [],
  },
  {
    name: "Quang Binh Province",
    code: 44,
    division_type: "province",
    codename: "quang_binh_province",
    phone_code: 232,
    districts: [],
  },
  {
    name: "Quang Tri Province",
    code: 45,
    division_type: "province",
    codename: "quang_tri_province",
    phone_code: 233,
    districts: [],
  },
  {
    name: "Thua Thien Hue Province",
    code: 46,
    division_type: "province",
    codename: "thua_thien_hue_province",
    phone_code: 234,
    districts: [],
  },
  {
    name: "Da Nang City",
    code: 48,
    division_type: "central city",
    codename: "da_nang_city",
    phone_code: 236,
    districts: [],
  },
  {
    name: "Quang Nam Province",
    code: 49,
    division_type: "province",
    codename: "quang_nam_province",
    phone_code: 235,
    districts: [],
  },
  {
    name: "Quang Ngai Province",
    code: 51,
    division_type: "province",
    codename: "quang_ngai_province",
    phone_code: 255,
    districts: [],
  },
  {
    name: "Binh Dinh Province",
    code: 52,
    division_type: "province",
    codename: "binh_dinh_province",
    phone_code: 256,
    districts: [],
  },
  {
    name: "Phu Yen Province",
    code: 54,
    division_type: "province",
    codename: "phu_yen_province",
    phone_code: 257,
    districts: [],
  },
  {
    name: "Khanh Hoa Province",
    code: 56,
    division_type: "province",
    codename: "khanh_hoa_province",
    phone_code: 258,
    districts: [],
  },
  {
    name: "Ninh Thuan Province",
    code: 58,
    division_type: "province",
    codename: "ninh_thuan_province",
    phone_code: 259,
    districts: [],
  },
  {
    name: "Binh Thuan Province",
    code: 60,
    division_type: "province",
    codename: "binh_thuan_province",
    phone_code: 252,
    districts: [],
  },
  {
    name: "Kon Tum Province",
    code: 62,
    division_type: "province",
    codename: "kon_tum_province",
    phone_code: 260,
    districts: [],
  },
  {
    name: "Gia Lai Province",
    code: 64,
    division_type: "province",
    codename: "gia_lai_province",
    phone_code: 269,
    districts: [],
  },
  {
    name: "Dak Lak Province",
    code: 66,
    division_type: "province",
    codename: "dak_lak_province",
    phone_code: 262,
    districts: [],
  },
  {
    name: "Dak Nong Province",
    code: 67,
    division_type: "province",
    codename: "dak_nong_province",
    phone_code: 261,
    districts: [],
  },
  {
    name: "Lam Dong Province",
    code: 68,
    division_type: "province",
    codename: "lam_dong_province",
    phone_code: 263,
    districts: [],
  },
  {
    name: "Binh Phuoc Province",
    code: 70,
    division_type: "province",
    codename: "binh_phuoc_province",
    phone_code: 271,
    districts: [],
  },
  {
    name: "Tay Ninh Province",
    code: 72,
    division_type: "province",
    codename: "tay_ninh_province",
    phone_code: 276,
    districts: [],
  },
  {
    name: "Binh Duong Province",
    code: 74,
    division_type: "province",
    codename: "binh_duong_province",
    phone_code: 274,
    districts: [],
  },
  {
    name: "Dong Nai Province",
    code: 75,
    division_type: "province",
    codename: "dong_nai_province",
    phone_code: 251,
    districts: [],
  },
  {
    name: "Ba Ria - Vung Tau Province",
    code: 77,
    division_type: "province",
    codename: "ba_ria_vung_tau_province",
    phone_code: 254,
    districts: [],
  },
  {
    name: "Ho Chi Minh City",
    code: 79,
    division_type: "central city",
    codename: "ho_chi_minh_city",
    phone_code: 28,
    districts: [],
  },
  {
    name: "Long An Province",
    code: 80,
    division_type: "province",
    codename: "long_an_province",
    phone_code: 272,
    districts: [],
  },
  {
    name: "Tien Giang Province",
    code: 82,
    division_type: "province",
    codename: "tien_giang_province",
    phone_code: 273,
    districts: [],
  },
  {
    name: "Ben Tre Province",
    code: 83,
    division_type: "province",
    codename: "ben_tre_province",
    phone_code: 275,
    districts: [],
  },
  {
    name: "Tra Vinh Province",
    code: 84,
    division_type: "province",
    codename: "tra_vinh_province",
    phone_code: 294,
    districts: [],
  },
  {
    name: "Vinh Long Province",
    code: 86,
    division_type: "province",
    codename: "vinh_long_province",
    phone_code: 270,
    districts: [],
  },
  {
    name: "Dong Thap Province",
    code: 87,
    division_type: "province",
    codename: "dong_thap_province",
    phone_code: 277,
    districts: [],
  },
  {
    name: "An Giang Province",
    code: 89,
    division_type: "province",
    codename: "an_giang_province",
    phone_code: 296,
    districts: [],
  },
  {
    name: "Kien Giang Province",
    code: 91,
    division_type: "province",
    codename: "kien_giang_province",
    phone_code: 297,
    districts: [],
  },
  {
    name: "Can Tho City",
    code: 92,
    division_type: "central city",
    codename: "can_tho_city",
    phone_code: 292,
    districts: [],
  },
  {
    name: "Hau Giang Province",
    code: 93,
    division_type: "province",
    codename: "hau_giang_province",
    phone_code: 291,
    districts: [],
  },
  {
    name: "Soc Trang Province",
    code: 94,
    division_type: "province",
    codename: "soc_trang_province",
    phone_code: 299,
    districts: [],
  },
  {
    name: "Bac Lieu Province",
    code: 95,
    division_type: "province",
    codename: "bac_lieu_province",
    phone_code: 291,
    districts: [],
  },
  {
    name: "Ca Mau Province",
    code: 96,
    division_type: "province",
    codename: "ca_mau_province",
    phone_code: 290,
    districts: [],
  },
];
